import Head from 'next/head'
import Hero from '@/components/Hero';
import Slider from '@/components/Slider';
import Insta from '@/components/Insta';
import { SliderData } from '@/sliderData';


export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Sahra photography" message="I capture moments in the nature and keep them alive" />
      <Slider slides={SliderData} />
      <Insta />
    </>
  )
}
